/**
 * Payload uses this importMap to load custom server / client components
 * referenced from the config (e.g. custom field components, dashboard tiles).
 *
 * It is regenerated by `pnpm payload generate:importmap` once we register
 * any custom components. Until then we ship an empty map so the admin boots.
 */
export const importMap = {};
